apiVersion: apps/v1
kind: Deployment
metadata:
  name: aipply-frontend-backend
  namespace: gitops-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: aipply-frontend-backend
  template:
    metadata:
      labels:
        app: aipply-frontend-backend
    spec:
      containers:
        - name: fe-be
          image: satheesh2003/aipply-frontend-backend:713e1ff
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: url
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: password
---
apiVersion: v1
kind: Service
metadata:
  name: fe-be-service
  namespace: gitops-demo
spec:
  selector:
    app: aipply-frontend-backend
  ports:
    - name: web
      port: 8080       # Service port
      targetPort: 8080 # Container port
      nodePort: 30080  # Minikube NodePort
  type: NodePort
