apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-mock-service
  namespace: gitops-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-mock-service
  template:
    metadata:
      labels:
        app: node-mock-service
    spec:
      containers:
        - name: mock
          image: satheesh2003/node-mock-service:latest
          ports:
            - containerPort: 3001   # your Dockerfile exposes 3001
---
apiVersion: v1
kind: Service
metadata:
  name: mock-service
  namespace: gitops-demo
spec:
  selector:
    app: node-mock-service
  ports:
    - port: 3001
      targetPort: 3001
  type: ClusterIP
