name: Build and Push Docker Images

on:
  push:
    branches:
      - main   # adjust if you use "master" or another branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repo
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Step 3: Create frontend .env file for Vite build
      - name: Create frontend .env
        run: |
          echo "VITE_BACKEND_URL=http://localhost:8080/api" > client/.env

      # Step 4: Build and push Fullstack (Frontend + Backend) image
      - name: Build and push fullstack app
        run: |
          IMAGE_NAME=satheesh2003/aipply-frontend-backend
          GIT_SHA=${{ github.sha }}
          docker build -t $IMAGE_NAME:latest -t $IMAGE_NAME:${GIT_SHA::7} .
          docker push $IMAGE_NAME:latest
          docker push $IMAGE_NAME:${GIT_SHA::7}

      # Step 5: Build and push NodeMockQuestionService image
      - name: Build and push NodeMockQuestionService
        run: |
          IMAGE_NAME=satheesh2003/aipply-nodemockservice
          GIT_SHA=${{ github.sha }}
          docker build -t $IMAGE_NAME:latest -t $IMAGE_NAME:${GIT_SHA::7} ./NodeMockQuestionService
          docker push $IMAGE_NAME:latest
          docker push $IMAGE_NAME:${GIT_SHA::7}
